### =============================================================
### This configuration file is used by CircleCI build server
### https://circleci.com/docs/config-sample
### =============================================================
version: 2.1
orbs:
  python: circleci/python@<< pipeline.parameters.python-orb-version >>
  node: circleci/node@<< pipeline.parameters.node-orb-version >>
  orb-tools: circleci/orb-tools@10.0

parameters:
  python-orb-version:
    type: string
    default: "2.0.3"
  node-orb-version:
    type: string
    default: "5.0.1"
  cache-version:
    type: string
    default: v4  # Change this parameter to clear cache.
  global-docker-image:
    type: string
    default: cimg/python:3.10-node

references:
  version_tag_regex: &version_tag_regex
                       /^v\d+\.\d+\.\d+$/ # version regex vx.x.x (i.e. v1.2.3)

  filter_tag_only: &filter_tag_only
    tags:
      only: *version_tag_regex

  tag_filter: &tag_filter
    filters:
      tags:
        only: *version_tag_regex

  install_poetry: &install_poetry
    - run:
        name: Install Poetry
        command: |
          # in old images we need to remove existing poetry
          rm -rf $HOME/.poetry/bin/poetry
          sudo curl -sSL https://install.python-poetry.org | python3 -
          poetry --version

  install_build_dependencies: &install_build_dependencies
    - python/install-packages:
        pkg-manager: "poetry"
        cache-version: << pipeline.parameters.cache-version >>
        pre-install-steps:
          - run:
              name: Check if pyproject.toml is consistent with poetry.lock
              command: poetry lock --check

jobs:
  run-unit-tests:
      parameters:
        pythonversion:
          type: string
      docker:
        - image: cimg/python:<< parameters.pythonversion >>-node
      steps:
        - checkout
        - <<: *install_poetry
        - <<: *install_build_dependencies
        - run:
            name: Pytest
            command: poetry run pytest -p no:warnings -v --cov=email_parser --cov-report=html
        - store_artifacts:
            path: coverage_html_report
        - run:
            name: Coveralls upload
            command: |
              if [ -n "$COVERALLS_REPO_TOKEN" ]; then
                pip install coveralls
                coveralls
              else
                echo "Skipping coveralls"
              fi
        - store_test_results:
            path: integration-test-results

  precommit-checks:
      docker:
        - image: << pipeline.parameters.global-docker-image >>
      steps:
        - checkout
        - <<: *install_poetry
        - attach_workspace:
            at: ~/project
        - <<: *install_build_dependencies
        - run:
            name: create cache key for pre-commit
            command: |
              cp .pre-commit-config.yaml pre-commit-cache-key.txt
              poetry run python --version --version >> pre-commit-cache-key.txt
        - restore_cache:
            keys:
            - v1-pc-cache-{{ checksum "pre-commit-cache-key.txt" }}
        - run:
            name: Pre-commit
            command: |
              poetry run pre-commit --version
              poetry run pre-commit run -a

        - run:
            name: Run Pytest collection
            command: |
                poetry run pytest --collect-only .

        - save_cache:
            key: v1-pc-cache-{{ checksum "pre-commit-cache-key.txt" }}
            paths:
              - ~/.cache/pre-commit

  build:
      docker:
        - image: << pipeline.parameters.global-docker-image >>
      steps:
          - checkout
          - run:
              name: Build Distrubution
              command: poetry build
          - persist_to_workspace:
              root: ~/project
              paths:
                - dist
          - store_artifacts:
              path: dist

  deploy:
      docker:
        - image: << pipeline.parameters.global-docker-image >>
      steps:
        - checkout
        - <<: *install_poetry
        - attach_workspace:
            at: ~/project
        - run:
            name: Deploy
            command: poetry publish -u __token__ -p ${PYPI_TOKEN}


workflows:
  version: 2.1
  build_and_release:
    jobs:
    - run-unit-tests:
        <<: *tag_filter
        matrix:
          parameters:
            pythonversion: ["3.8", "3.9", "3.10"]
        name: run-unit-tests-<< matrix.pythonversion >>
    - precommit-checks:
        <<: *tag_filter
    - build:
        <<: *tag_filter
    - deploy:
        filters:
            tags:
              only: *version_tag_regex
            branches:
              ignore: /.*/
        requires:
          - run-unit-tests
          - build
          - precommit-checks